(require 'color-theme)
;;(load-file "~/.emacs.d/vendor/color-theme/themes/color-theme-railscasts.el")
(load-file "~/.emacs.d/vendor/color-theme/themes/color-theme-tangotango.el")
;;(color-theme-railscasts)
(color-theme-tangotango)
